### PR TITLE
Fix black color handling

### LINKED ISSUE #198: TestNethackTerminalObservation.test_crop flaky
## 🐛 Bug

The `test_nethack.py::TestNethackTerminalObservation.test_crop` test is somewhat flaky ([example logs](https://pipelines.actions.githubusercontent.com/y49V3CuIOIsnG2Ggy0ZW3D0rxfq87ro7x2vjHKJeVxqUdbgAYo/_apis/pipelines/1/runs/5760/signedlogcontent/4?urlExpires=2021-07-08T17%3A33%3A09.8527021Z&urlSigningMethod=HMACV1&urlSignature=SnAVG0oHYSwbx9d%2BhlAvMsVXxlNWG1lq1Eb%2BxE5q0qM%3D)):

```
2021-07-08T17:28:07.7259580Z nle/tests/test_envs.py ................................................. [ 33%]
2021-07-08T17:28:17.1660260Z ......................................................................   [ 80%]
2021-07-08T17:28:21.7517690Z nle/tests/test_nethack.py ...................F...                        [ 96%]
2021-07-08T17:29:11.4360120Z nle/tests/test_profile.py .....                                          [100%]
2021-07-08T17:29:11.4360870Z 
2021-07-08T17:29:11.4361690Z =================================== FAILURES ===================================
2021-07-08T17:29:11.4363020Z ___________________ TestNethackTerminalObservation.test_crop ___________________
2021-07-08T17:29:11.4364220Z 
2021-07-08T17:29:11.4366240Z self = <test_nethack.TestNethackTerminalObservation object at 0x10ce24810>
2021-07-08T17:29:11.4368080Z game = <nle.nethack.nethack.Nethack object at 0x10ce4af10>
2021-07-08T17:29:11.4368940Z 
2021-07-08T17:29:11.4369650Z     def test_crop(self, game):
2021-07-08T17:29:11.4371090Z         tty_chars, tty_colors, _, chars, colors = game.reset()
2021-07-08T17:29:11.4372010Z     
2021-07-08T17:29:11.4373790Z         g_chars = chars.reshape(-1)
2021-07-08T17:29:11.4375160Z         g_cols = colors.reshape(-1)
2021-07-08T17:29:11.4375590Z     
2021-07-08T17:29:11.4376100Z         # DUNGEON is [21, 79], TTY is [24, 80]. Crop as follows  to get alignment.
2021-07-08T17:29:11.4377050Z         t_chars = tty_chars[1:-2, :-1].reshape(-1)
2021-07-08T17:29:11.4378040Z         t_cols = tty_colors[1:-2, :-1].reshape(-1)
2021-07-08T17:29:11.4378730Z     
2021-07-08T17:29:11.4379560Z         for g_char, g_col, t_char, t_col in zip(g_chars, g_cols, t_chars, t_cols):
2021-07-08T17:29:11.4380490Z             assert g_char == t_char
2021-07-08T17:29:11.4381440Z >           assert g_col == t_col
2021-07-08T17:29:11.4382290Z E           assert 0 == 7
2021-07-08T17:29:11.4382660Z 
2021-07-08T17:29:11.4383610Z /Users/runner/work/nle/nle/nle/tests/test_nethack.py:451: AssertionError
```

## To Reproduce

In zsh syntax

```
repeat 50 python `which pytest` -svx 'nle/tests/test_nethack.py::TestNethackTerminalObservation::test_crop' --pdb
```

## Expected behavior

Only perfect nonflaky tests, like in every FAIR project.

### PR DESCRIPTION
**Pull request by heiner**
Handle black items correctly.

When using `ANSI_DEFAULT`, `hilites[CLR_BLACK]` was set as a `NULL` string. This caused black items to show up as gray. I sent a fix to upstream NetHack at https://github.com/NetHack/NetHack/pull/556.

Fixing that alone doesn't unbreak `test_nethack.py::TestNethackTerminalObservation::test_crop` (which broke whenever black items were in sight) since `CLR_BLACK` is 0, not 8 aka bright black (and also `NO_COLOR`, somewhat confusingly).

We fix this by changing the output of `mapglyph` for glyphs that aren't the null glyph.

Fixes #198.

Also fix `read_tty.py` (broken after https://github.com/facebookresearch/nle/pull/217) and simplify test_crop.

### CODE REVIEW

File: win/rl/winrl.cc [hunk 1]
```diff
@@ -930,6 +930,11 @@ NetHackRL::rl_print_glyph(winid wid, XCHAR_P x, XCHAR_P y, int glyph,
     // No win_proc_calls entry here.
     if (wid == WIN_MAP) {
         instance->store_glyph(x, y, glyph);
+        if (glyph != nul_glyph && color == CLR_BLACK) {
+            /* This will be 'bright black' (or blue) on tty so we change it to
+             * make NLE's colors and tty_colors stay compatible. */
+            color = iflags.wc2_darkgray ? 8 : CLR_BLUE;
```
Comment (condnsdmatters) [inline win/rl/winrl.cc:936]: or `CLR_BLUE`?!?

File: src/nle.c [hunk 2]
```diff
@@ -46,32 +46,35 @@ vt_char_color_extract(TMTCHAR *c)
...
-            (c->c == 32) ? CLR_BLACK : CLR_GRAY; // ' ' is BLACK else WHITE
+        color = (c->c == ' ') ? CLR_BLACK : CLR_GRAY; /* ' ' is 0 else 7 */
         break;
     case (TMT_COLOR_BLACK):
-        color = (c->a.bold) ? NO_COLOR : CLR_BLACK; // c = 8:0
+        /* "bright black" is dark gray. Non-bright black is black and
+           therefore invisible on the assumed black background. NetHack
+           shouldn't use it. So we assume bright black, which is 8 (also,
+           confusingly, NO_COLOR, but that's an aside). */
+        color = 8;
```
Comment (condnsdmatters) [inline src/nle.c:56]: Does NH never use `CLR_BLACK`? In `colors.h` it is defined and in `mapglyph.c` it looks like its used for some kinds of explosions... Why do we need to be rid of this logic?

File: win/rl/winrl.cc (hunk 1 above)
Comment (condnsdmatters) [reply win/rl/winrl.cc:936]: I will read the termcap fix

File: win/tty/termcap.c [hunk 3]
```diff
@@ -1166,7 +1176,12 @@ kill_hilite()
         if (hilites[c | BRIGHT] && hilites[c | BRIGHT] != nh_HI)
             free((genericptr_t) hilites[c | BRIGHT]), hilites[c | BRIGHT] = 0;
     }
-    return;
+
+    if (hilites[CLR_BLACK]) {
```
Comment (condnsdmatters) [inline win/tty/termcap.c:1180]: nice catch on the dealloc.

**Review by condnsdmatters — APPROVED** [review]

File: win/rl/winrl.cc (hunk 1 above)
Comment (heiner) [reply win/rl/winrl.cc:936]: NetHack has a configuration option on whether it uses "bright black" (`\033[1;30m`) or (dark) blue to display black entries: https://github.com/facebookresearch/nle/blob/master/win/tty/termcap.c#L887

File: src/nle.c (hunk 2 above)
Comment (heiner) [reply src/nle.c:56]: Some objects and monsters are black. E.g. Orcish arrow (https://github.com/facebookresearch/nle/blob/master/src/objects.c#L117) or (duh!), black dragons and unicorns (https://github.com/facebookresearch/nle/blob/master/src/monst.c#L1219, https://github.com/facebookresearch/nle/blob/master/src/monst.c#L839).

File: win/tty/termcap.c (hunk 3 above)
Comment (heiner) [reply win/tty/termcap.c:1180]: (Not sure if that's clear already, but: This dealloc is only necessary / correct given the other changes in this commit. Before, `hilites[CLR_BLACK]` was always `NULL` for the macro definitions we use.)

File: src/nle.c (hunk 2 above)
Comment (heiner) [reply src/nle.c:56]: So yes, it very much uses `CLR_BLACK`. Before this change, it would display them as gray/default in the tty output (which is more or less a bug in NetHack, triggered by our non-standard macro definitions). After fixing this, `CLR_BLACK` might come out as `8` (= bright black) in the tty, again not the same as `CLR_BLACK` (which is 0). Hence the change in winrl.cc.

File: win/rl/winrl.cc (hunk 1 above)
Comment (heiner) [reply win/rl/winrl.cc:936]: For clarity, here's a Python version of what this code here did before this change:

```python
CLR_BLACK = 0
CLR_RED = 1
CLR_GREEN = 2
CLR_BROWN = 3  # /* on IBM, low-intensity yellow is brown */
CLR_BLUE = 4
CLR_MAGENTA = 5
CLR_CYAN = 6
CLR_GRAY = 7  # /* low-intensity white */
NO_COLOR = 8
CLR_ORANGE = 9
CLR_BRIGHT_GREEN = 10
CLR_YELLOW = 11
CLR_BRIGHT_BLUE = 12
CLR_BRIGHT_MAGENTA = 13
CLR_BRIGHT_CYAN = 14
CLR_WHITE = 15
CLR_MAX = 16

BRIGHT = 8

hilites = [None] * 16

hilites[CLR_GRAY] = ""
hilites[NO_COLOR] = hilites[CLR_GRAY]

for c in range(CLR_MAX // 2):
    if c == CLR_BLACK:
        continue
    hilites[c | BRIGHT] = "\033[1;3%dm" % c
    if c == CLR_GRAY:
        continue
    hilites[c] = "\033[0;3%dm" % c

print(hilites)
```

File: src/nle.c (hunk 2 above)
Comment (heiner) [reply src/nle.c]: OK, revised the changes to nle.c (it's now using the `BRIGHT` logic).

**Review by condnsdmatters — APPROVED** [review]
